Repository svrxjs/svrx, pull requests merged in 2019-09, with the labels that each got.

#76 Rename package-lock to npm-shrinkwrap
  npm-shrinkwrap.json
  packages/svrx-util/npm-shrinkwrap.json
  packages/svrx/npm-shrinkwrap.json
Labels: PR: internal

#77 Fix number check for option value
  packages/svrx/__tests__/spec/svrx.configure.js
  packages/svrx/lib/configure/index.js
Labels: PR: bug fix

#83 Return the right package info after npmi
  packages/svrx-util/__tests__/spec/npm.test.js
  packages/svrx-util/lib/npm/index.js
  packages/svrx/lib/plugin/npm.js
Labels: PR: bug fix

#84 Fix dashed plugin name parse error
  packages/svrx/__tests__/spec/svrx.configure.js
  packages/svrx/__tests__/spec/svrx.utility.js
  packages/svrx/lib/configure/index.js
  packages/svrx/lib/util/helper.js
Labels: PR: bug fix

#86 feat: alias registService to regist
  packages/svrx/__tests__/spec/svrx.io.js
  packages/svrx/lib/io/index.js
Labels: PR: new feature

#99 Rename every 'x-orpheus' to 'svrxjs'
  CHANGELOG.md
  LICENSE
  README.md
  lerna.json
  packages/svrx-util/package.json
  packages/svrx/lib/svrx.js
  packages/svrx/package.json
Labels: PR: internal

#102 Rename badges
  README.md
Labels: PR: documentation

#104 perf: use native api insted of user-home
  packages/svrx-util/lib/rc-file-read.js
  packages/svrx-util/npm-shrinkwrap.json
  packages/svrx-util/package.json
Labels: PR: internal

#105 chore: test on node v12
  .travis.yml
Labels: PR: internal

#108 Denpendency update & npm audit fix
  npm-shrinkwrap.json
  package.json
  packages/svrx-util/npm-shrinkwrap.json
  packages/svrx-util/package.json
  packages/svrx/npm-shrinkwrap.json
  packages/svrx/package.json
Labels: PR: dependencies
