Repository svrxjs/svrx, pull requests merged in 2019-11, with the labels that each got.

#145 fix: fix windows path parse error
  packages/svrx/lib/router/loader.js
Labels: PR: bug fix

#146 publish v1.0.6
  CHANGELOG.md
  lerna.json
  packages/svrx-util/package.json
  packages/svrx/package.json
Labels: PR: internal

#148 Replace global-npm.install with npminstall
  packages/svrx-util/__tests__/spec/npm.test.js
  packages/svrx-util/__tests__/spec/readJSON.test.js
  packages/svrx-util/lib/npm/index.js
  packages/svrx-util/lib/readJSON.js
  packages/svrx-util/lib/svrx-util.js
  packages/svrx-util/package.json
Labels: PR: bug fix

#149 Release/1.0.7
  CHANGELOG.md
  lerna.json
  packages/svrx-util/package.json
  packages/svrx/package.json
Labels: PR: internal

#152 Change plugin install strategy to global install
  package.json
  packages/svrx-util/__tests__/fixture/.svrx/config/.svrxrc.js
  packages/svrx-util/__tests__/fixture/.svrx/plugins/hello/0.0.5/index.js
  packages/svrx-util/__tests__/fixture/.svrx/plugins/hello/0.0.5/package.json
  packages/svrx-util/__tests__/fixture/.svrx/plugins/hello/1.0.0/index.js
  packages/svrx-util/__tests__/fixture/.svrx/plugins/hello/1.0.0/package.json
  packages/svrx-util/__tests__/fixture/.svrx/plugins/hello/1.0.1/index.js
  packages/svrx-util/__tests__/fixture/.svrx/plugins/hello/1.0.1/package.json
  packages/svrx-util/__tests__/fixture/plugin/svrx-plugin-error-no-version/index.js
  packages/svrx-util/__tests__/fixture/plugin/svrx-plugin-error-no-version/package.json
  packages/svrx-util/__tests__/fixture/plugin/svrx-plugin-no-package/index.js
  packages/svrx-util/__tests__/spec/name-formatter.test.js
  packages/svrx-util/__tests__/spec/npm.test.js
  packages/svrx-util/__tests__/spec/package-manager.test.js
  packages/svrx-util/__tests__/spec/readJSON.test.js
  packages/svrx-util/lib/name-formatter.js
  packages/svrx-util/lib/npm/index.js
  packages/svrx-util/lib/package-manager/index.js
  packages/svrx-util/lib/package-manager/package-manager.js
  packages/svrx-util/lib/package-manager/plugin-package-manager.js
  packages/svrx-util/lib/package-manager/tasks/install.js
  packages/svrx-util/lib/package-manager/tasks/view.js
  packages/svrx-util/lib/rc-file-read.js
  packages/svrx-util/lib/readJSON.js
  packages/svrx-util/lib/svrx-util.js
  packages/svrx-util/package.json
  packages/svrx/__tests__/spec/svrx.base.js
  packages/svrx/__tests__/spec/svrx.plugin.js
  packages/svrx/__tests__/spec/svrx.utility.js
  packages/svrx/lib/configure/index.js
  packages/svrx/lib/plugin/devnull.js
  packages/svrx/lib/plugin/loader.js
  packages/svrx/lib/plugin/npm.js
  packages/svrx/lib/plugin/system.js
  packages/svrx/lib/router/route.js
  packages/svrx/lib/util/helper.js
  packages/svrx/package.json
Labels: PR: new feature

#151 fix: upgrade the priority of builtin api
  packages/svrx/__tests__/spec/svrx.router.js
  packages/svrx/lib/constant.js
  packages/svrx/lib/io/index.js
  packages/svrx/lib/router/loader.js
Labels: PR: internal

#153 chore(release): publish v1.1.0
  CHANGELOG.md
  lerna.json
  package.json
  packages/svrx-util/package.json
  packages/svrx/package.json
Labels: PR: internal

#156 Support svrx-cli for core package installation
  packages/svrx-util/__tests__/fixture/.svrx/config/.svrxrc.js
  packages/svrx-util/__tests__/fixture/.svrx/versions/1.0.6/index.js
  packages/svrx-util/__tests__/fixture/.svrx/versions/1.0.6/lib/svrx.js
  packages/svrx-util/__tests__/fixture/.svrx/versions/1.0.6/package.json
  packages/svrx-util/__tests__/spec/package-manager.test.js
  packages/svrx-util/__tests__/spec/rc-file-read.test.js
  packages/svrx-util/lib/c2k.js
  packages/svrx-util/lib/package-manager/index.js
  packages/svrx-util/lib/package-manager/package-manager.js
  packages/svrx/lib/config-list.js
  packages/svrx/lib/util/jsonSchemaDefaults.js
Labels: PR: internal

#161 build: perf the pr and issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
Labels: PR: internal

#160 Update lerna and path-to-regex
  package.json
  packages/svrx/package.json
Labels: PR: dependencies

#159 Add autoclean to package-manager
  packages/svrx-util/__tests__/spec/package-manager.test.js
  packages/svrx-util/lib/package-manager/package-manager.js
Labels: PR: new feature

#162 Update to 1.1.1
  CHANGELOG.md
  lerna.json
  packages/svrx-util/package.json
  packages/svrx/package.json
Labels: PR: internal

#163 Enable auto clean on local package load
  packages/svrx-util/__tests__/spec/package-manager.test.js
  packages/svrx-util/lib/package-manager/package-manager.js
Labels: PR: internal
