Repository svrxjs/svrx, pull requests merged in 2019-10, with the labels that each got.

#107 docs: add dependency badge and update readmes
  README.md
  packages/svrx-util/README.md
  packages/svrx/README.md
Labels: PR: documentation

#110 Add watch(), del(), splice() to config
  .eslintignore
  packages/svrx-util/npm-shrinkwrap.json
  packages/svrx-util/package.json
  packages/svrx/__tests__/spec/configure/builtinConfig.js
  packages/svrx/__tests__/spec/configure/cli.js
  packages/svrx/__tests__/spec/configure/inline.js
  packages/svrx/__tests__/spec/configure/pluginConfig.js
  packages/svrx/lib/configure/index.js
  packages/svrx/lib/configure/plugin.js
  packages/svrx/npm-shrinkwrap.json
  packages/svrx/package.json
Labels: PR: new feature

#106 Refactor plugin package name parse
  codecov.yml
  packages/svrx/__tests__/spec/configure/inline.js
  packages/svrx/__tests__/spec/svrx.utility.js
  packages/svrx/lib/configure/index.js
  packages/svrx/lib/util/helper.js
Labels: PR: internal

#111 Use local npm instead of npm & npmi
  packages/svrx-util/lib/npm/index.js
  packages/svrx-util/npm-shrinkwrap.json
  packages/svrx-util/package.json
  packages/svrx/npm-shrinkwrap.json
Labels: PR: internal

#115 remove npm-shrinkwrap.json
  .eslintrc
  .gitignore
  package-lock.json
  package.json
  packages/svrx-util/package-lock.json
  packages/svrx-util/package.json
  packages/svrx/npm-shrinkwrap.json
  packages/svrx/package-lock.json
  packages/svrx/package.json
Labels: PR: internal

#117 remove package-lock
  .gitignore
  .npmrc
  .travis.yml
  CHANGELOG.md
  package-lock.json
  package.json
  packages/svrx-util/.npmrc
  packages/svrx-util/package-lock.json
  packages/svrx/.npmrc
  packages/svrx/package-lock.json
Labels: PR: internal

#119 fix: routing update not working
  packages/svrx/lib/router/loader.js
Labels: PR: bug fix

#129 Prevent modify package.json when plugin installation
  packages/svrx-util/lib/npm/index.js
Labels: PR: bug fix

#130 Add content to readme
  .github/ISSUE_TEMPLATE/bug_report.md
  README.md
Labels: PR: documentation

#132 Fix process exit not working on Windows
  packages/svrx/__tests__/spec/svrx.base.js
  packages/svrx/index.js
Labels: PR: bug fix

#135 Fix not working on Windows
  packages/svrx-util/lib/rc-file-read.js
  packages/svrx/lib/configure/index.js
  packages/svrx/scripts/webpack.injector.js
Labels: PR: bug fix

#138 chore(release): publish v1.0.5
  lerna.json
  packages/svrx-util/package.json
  packages/svrx/package.json
Labels: PR: internal

#139 Add changelog for 1.0.5
  CHANGELOG.md
Labels: PR: documentation
