Repository svrxjs/svrx, pull requests merged in 2019-07, with the labels that each got.

#1 Feature/router
  .eslintignore
  packages/svrx-plugin-webpack/package-lock.json
  packages/svrx/__tests__/fixture/router/rule.normal.js
  packages/svrx/__tests__/fixture/router/static/index.html
  packages/svrx/__tests__/spec/svrx.router.js
  packages/svrx/__tests__/util.js
  packages/svrx/lib/plugin/svrx-plugin-serve/index.js
  packages/svrx/lib/plugin/system.js
  packages/svrx/lib/router/actions.js
  packages/svrx/lib/router/index.js
  packages/svrx/lib/router/loader.js
  packages/svrx/lib/router/methods.js
  packages/svrx/lib/router/route.js
  packages/svrx/lib/router/router.js
  packages/svrx/lib/shared/cache.js
  packages/svrx/lib/svrx.js
  packages/svrx/lib/util/compose.js
  packages/svrx/lib/util/helper.js
  packages/svrx/package-lock.json
  packages/svrx/package.json
Labels: PR: enhancement

#8 perf(cli): enhance help print
  package.json
  packages/svrx-cli/bin/svrx.js
  packages/svrx-cli/lib/index.js
  packages/svrx-cli/package-lock.json
  packages/svrx/lib/config-list.js
  packages/svrx/lib/svrx.js
Labels: PR: enhancement

#10 Feature/leeluolee 0.0.4
  packages/svrx-plugin-webpack/index.js
  packages/svrx-plugin-webpack/package.json
  packages/svrx/README.md
  packages/svrx/__tests__/spec/svrx.base.js
  packages/svrx/__tests__/spec/svrx.io.js
  packages/svrx/__tests__/spec/svrx.plugin.js
  packages/svrx/__tests__/spec/svrx.utility.js
  packages/svrx/__tests__/util.js
  packages/svrx/lib/config-list.js
  packages/svrx/lib/constant.js
  packages/svrx/lib/io/client.js
  packages/svrx/lib/io/index.js
  packages/svrx/lib/plugin/svrx-plugin-livereload/assets/index.js
  packages/svrx/lib/plugin/svrx-plugin-livereload/index.js
  packages/svrx/lib/plugin/svrx-plugin-open/index.js
  packages/svrx/lib/plugin/svrx-plugin-proxy/index.js
  packages/svrx/lib/shared/cache.js
  packages/svrx/lib/shared/consts.js
  packages/svrx/lib/shared/events.js
  packages/svrx/lib/svrx.js
  packages/svrx/lib/util/helper.js
  packages/svrx/package-lock.json
  packages/svrx/package.json
Labels: PR: enhancement

#11 feat(cli): add --plugin to define plugin and options
  examples/proxy/public/main.js
  packages/svrx/__tests__/spec/svrx.configure.js
  packages/svrx/lib/config-list.js
  packages/svrx/lib/configure/index.js
Labels: PR: new feature

#9 feat(cli): add global rc config
  packages/svrx-cli/bin/svrx.js
  packages/svrx-cli/lib/config.js
  packages/svrx-cli/lib/index.js
  packages/svrx-cli/package-lock.json
  packages/svrx-cli/package.json
  packages/svrx-plugin-webpack/package-lock.json
  packages/svrx-toolkit/package-lock.json
  packages/svrx-ui/package-lock.json
  packages/svrx-util/lib/rc-file-read.js
  packages/svrx-util/lib/svrx-util.js
  packages/svrx-util/package-lock.json
  packages/svrx-util/package.json
  packages/svrx/lib/svrx.js
  packages/svrx/package-lock.json
  packages/svrx/package.json
Labels: PR: enhancement

#12 feat(proxy): add proxy action
  packages/svrx/__tests__/spec/svrx.plugin.proxy.js
  packages/svrx/lib/plugin/svrx-plugin-proxy/index.js
  packages/svrx/package-lock.json
  packages/svrx/package.json
Labels: PR: new feature

#19 fix(core): #18 , `https` not working
  packages/svrx/package.json
Labels: PR: bug fix

#17 fix(io): set charset for injected script
  packages/svrx/lib/injector/index.js
Labels: PR: bug fix

#20 Add changelog
  CHANGELOG.md
Labels: PR: documentation

#15 test(config): add testcases
  packages/svrx-util/lib/rc-file-read.js
  packages/svrx/__tests__/spec/svrx.configure.js
  packages/svrx/lib/config-list.js
  packages/svrx/lib/configure/index.js
  packages/svrx/lib/configure/option.js
  packages/svrx/lib/configure/plugin.js
Labels: PR: internal

#21 0.0.5
  CHANGELOG.md
  lerna.json
  packages/svrx-util/package-lock.json
  packages/svrx-util/package.json
  packages/svrx/package-lock.json
  packages/svrx/package.json
Labels: PR: internal

#23 Add plugin version match check
  packages/svrx/__tests__/spec/svrx.plugin.js
  packages/svrx/lib/plugin/system.js
Labels: PR: enhancement

#22 Fix config.get() to get all default values
  packages/svrx/__tests__/fixture/plugin/svrx-plugin-depend/index.js
  packages/svrx/__tests__/fixture/plugin/svrx-plugin-test/index.js
  packages/svrx/__tests__/spec/svrx.configure.js
  packages/svrx/__tests__/util.js
  packages/svrx/lib/configure/index.js
  packages/svrx/lib/configure/plugin.js
Labels: PR: bug fix
