Repository svrxjs/svrx, pull requests merged in 2019-08, with the labels that each got.

#25 feat(open): support relative path to open
  packages/svrx/__tests__/spec/svrx.plugin.js
  packages/svrx/lib/plugin/svrx-plugin-open/index.js
Labels: PR: enhancement

#27 Fix router not work when historyfallback set to true
  packages/svrx/lib/constant.js
  packages/svrx/lib/plugin/svrx-plugin-serve/index.js
  packages/svrx/lib/svrx.js
Labels: PR: bug fix

#26 Fix parse plugin querystring with dot string
  packages/svrx/__tests__/spec/svrx.configure.js
  packages/svrx/lib/configure/index.js
Labels: PR: bug fix

#28 Multiple install
  packages/svrx-util/lib/logger.js
  packages/svrx/__tests__/spec/svrx.plugin.js
  packages/svrx/lib/plugin/loader.js
  packages/svrx/lib/plugin/npm.js
  packages/svrx/lib/plugin/svrx-plugin-open/index.js
  packages/svrx/lib/plugin/system.js
  packages/svrx/lib/plugin/task.js
Labels: PR: enhancement

#29 Coverage to 90
  packages/svrx/__tests__/fixture/plugin/svrx-plugin-no-package/index.js
  packages/svrx/__tests__/spec/svrx.base.js
  packages/svrx/__tests__/spec/svrx.injector.js
  packages/svrx/__tests__/spec/svrx.io.js
  packages/svrx/__tests__/spec/svrx.plugin.js
  packages/svrx/__tests__/spec/svrx.utility.js
  packages/svrx/lib/injector/index.js
  packages/svrx/lib/plugin/npm.js
  packages/svrx/lib/plugin/task.js
  packages/svrx/lib/svrx.js
  packages/svrx/lib/util/helper.js
  packages/svrx/lib/util/im.js
Labels: PR: internal

#31 Add codecov support
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  packages/svrx-util/package.json
  packages/svrx/lib/plugin/npm.js
  packages/svrx/package.json
Labels: PR: internal

#42 Add license and badges
  LICENSE
  README.md
  codecov.yml
Labels: PR: internal

#53 Feature/update readme
  README.md
Labels: PR: documentation

#57 build(dev-deps): remove coveralls
  package-lock.json
  package.json
Labels: PR: dependencies

#54 Bump eslint
  .eslintrc
  examples/proxy/public/main.js
  package-lock.json
  package.json
  packages/svrx-util/lib/npm/index.js
  packages/svrx-util/lib/rc-file-read.js
  packages/svrx/__tests__/spec/svrx.base.js
  packages/svrx/__tests__/spec/svrx.configure.js
  packages/svrx/__tests__/spec/svrx.injector.js
  packages/svrx/__tests__/spec/svrx.io.js
  packages/svrx/__tests__/spec/svrx.plugin.js
  packages/svrx/__tests__/spec/svrx.plugin.proxy.js
  packages/svrx/__tests__/spec/svrx.router.js
  packages/svrx/index.js
  packages/svrx/lib/configure/index.js
  packages/svrx/lib/configure/option.js
  packages/svrx/lib/injector/index.js
  packages/svrx/lib/middleware/index.js
  packages/svrx/lib/model.js
  packages/svrx/lib/plugin/loader.js
  packages/svrx/lib/plugin/npm.js
  packages/svrx/lib/plugin/svrx-plugin-open/index.js
  packages/svrx/lib/plugin/svrx-plugin-proxy/index.js
  packages/svrx/lib/plugin/system.js
  packages/svrx/lib/router/actions.js
  packages/svrx/lib/router/loader.js
  packages/svrx/lib/router/router.js
  packages/svrx/lib/shared/cache.js
  packages/svrx/lib/svrx.js
  packages/svrx/lib/util/helper.js
  packages/svrx/lib/util/im.js
  packages/svrx/lib/util/jsonSchemaDefaults.js
  packages/svrx/lib/util/semver.js
Labels: PR: internal

#66 Set default value of proxy.changeOrigin to true
  examples/proxy/.svrxrc.js
  packages/svrx-util/package-lock.json
  packages/svrx/__tests__/spec/svrx.plugin.proxy.js
  packages/svrx/lib/plugin/svrx-plugin-proxy/index.js
  packages/svrx/package-lock.json
Labels: PR: breaking change

#30 Add testcases for plugin proxy
  packages/svrx/__tests__/spec/svrx.plugin.proxy.js
Labels: PR: internal

#68 Publish v0.0.7
  CHANGELOG.md
  lerna.json
  packages/svrx-util/package-lock.json
  packages/svrx-util/package.json
  packages/svrx/package-lock.json
  packages/svrx/package.json
Labels: PR: internal
